FROM centos
MAINTAINER Admin <admin@admin.com>
CMD echo "now running..."

RUN yum install -y httpd
RUN echo "Hellow container !" > /var/www/html/index.html
EXPOSE 80
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
