FROM centos
MAINTAINER Admin <admin@admin.com>
RUN yum install -y python3
RUN yum install -y httpd
RUN echo "Hellow container !" > /var/www/html/index.html
EXPOSE 80
COPY startup.sh /startup.sh
RUN chmod 744 /startup.sh
CMD ["/startup.sh"]
